apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-switch-software-pvc
  namespace: switch-software
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: local-path
