apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-switch-software-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
