apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-switch-software-sts
spec:
  selector:
    matchLabels:
      app: postgres-switch-software-sts
  serviceName: "postgres-switch-software-svc"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: postgres-switch-software-sts # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres-switch-software-sts
          image: postgres:15.3
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                  configMapKeyRef:
                    name: postgres-configmap
                    key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgresdb
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-switch-software-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: postgres-switch-software-svc
spec:
  selector:
    app: postgres-switch-software-sts
  type: ClusterIP
  ports:
    - name: postgres-switch-software-dns
      protocol: TCP
      port: 5432
      targetPort: 5432

#---
#apiVersion: networking.k8s.io/v1
#kind: NetworkPolicy
#metadata:
#  name: postgres-switch-software-np
#spec:
#  podSelector:
#    matchLabels:
#      app: postgres-switch-software-svc
#  ingress:
#    - from:
#        - namespaceSelector:     # chooses all pods in namespaces labelled with team=operations
#            matchLabels:
#              app: switch-software
#        - podSelector:
#            matchLabels:
#              postgres: "true"