#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: redis-config
#data:
#  redis.conf: |
#    requirepass "$(REDIS_PASSWORD)"
#
#---
apiVersion: v1
stringData:
  REDIS_PASSWORD: "xxxxxxxxxxxxxxxxxxxxxx"
kind: Secret
metadata:
  name: redis-secret
type: Opaque

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-switch-software-sts
spec:
  selector:
    matchLabels:
      app: redis-switch-software-sts
  serviceName: "redis-switch-software-svc"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: redis-switch-software-sts
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis:7.0.12-alpine
        command:
          - redis-server
        args:
          - --requirepass
          - $(REDIS_PASSWORD)
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_PASSWORD
        ports:
        - containerPort: 6379
#        volumeMounts:
#        - name: redis-config-volume
#          mountPath: /usr/local/etc/redis/
#      volumes:
#      - name: redis-config-volume
#        configMap:
#          name: redis-config
---
kind: Service
apiVersion: v1
metadata:
  name: redis-switch-software-svc
spec:
  selector:
    app: redis-switch-software-sts
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
